services:
    web:
        container_name: Tomcat-IIQ-${IIQ_VERSION}
        depends_on:
            - db
        image: sbadiyan/tomcat-iiq:${IIQ_VERSION}
        #build: ./tomcat
        ports:
            - "8080:8080"
        command: ["/home/mysql-ping.sh"]
        volumes:
            - db_vol:/var/lib/mysql
            - iiq_vol:/usr/local/tomcat/webapps/identityiq
        links:
            - db
    db:
        container_name: MySQL-IIQ-${IIQ_VERSION}
        image: sbadiyan/mysql-iiq:${IIQ_VERSION}
        #build: ./mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT: root
            MYSQL_ROOT_PASSWORD: root
        cap_add:
            - SYS_NICE
        volumes:
            - db_vol:/var/lib/mysql
            - iiq_vol:/usr/local/tomcat/webapps/identityiq
volumes:
    db_vol:
    iiq_vol: