services:
    web:
        container_name: tomcat
        depends_on:
            - db
        build: ./tomcat
        ports:
            - "${TOMCAT_APPLICATION_PORT}:8080"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT: ${MYSQL_ROOT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: ["/home/mysql-ping.sh"]
        volumes:
            - db_vol:/var/lib/mysql
            - iiq_vol:/usr/local/tomcat/webapps/identityiq
        links:
            - db
    db:
        container_name: mysql
        image: mysql:${MYSQL_VERSION}
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT: ${MYSQL_ROOT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        volumes:
            - db_vol:/var/lib/mysql
            - iiq_vol:/usr/local/tomcat/webapps/identityiq
            - ./mysql/mysql-dump:/docker-entrypoint-initdb.d
    # phpmyadmin:
    #     container_name: phpmyadmin
    #     depends_on:
    #         - db
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - '${PHPMYADMIN_APPLICATION_PORT}:80'
    #     environment:
    #         PMA_HOST: db
    #         MYSQL_ROOT: ${MYSQL_ROOT}
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
    db_vol:
    iiq_vol: